# 默认服务端口
server:
  port: 8080
  servlet:
    context-path : /ffpay
  tomcat:
    uri-encoding : utf-8
    
# Spring配置
spring:
  thymeleaf:
    mode: LEGACYHTML5
    cache: false

  # 配置数据源
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
      # Mysql
      url: jdbc:mysql://db-cuhk-afi.c18nldkzqsg2.us-east-1.rds.amazonaws.com:3306/project?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
      username: admin
      password: cuhk1001
      initialSize: 1
      minIdle: 3
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,slf4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
